//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package calm

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, client, ttlMinutes
func (_m *MockClient) CreateSession(ctx context.Context, client string, ttlMinutes int) (string, error) {
	ret := _m.Called(ctx, client, ttlMinutes)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return rf(ctx, client, ttlMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(ctx, client, ttlMinutes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, client, ttlMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockClient_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - client string
//   - ttlMinutes int
func (_e *MockClient_Expecter) CreateSession(ctx interface{}, client interface{}, ttlMinutes interface{}) *MockClient_CreateSession_Call {
	return &MockClient_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, client, ttlMinutes)}
}

func (_c *MockClient_CreateSession_Call) Run(run func(ctx context.Context, client string, ttlMinutes int)) *MockClient_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockClient_CreateSession_Call) Return(sessionToken string, err error) *MockClient_CreateSession_Call {
	_c.Call.Return(sessionToken, err)
	return _c
}

func (_c *MockClient_CreateSession_Call) RunAndReturn(run func(context.Context, string, int) (string, error)) *MockClient_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, sessionToken
func (_m *MockClient) DeleteSession(ctx context.Context, sessionToken string) error {
	ret := _m.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockClient_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
func (_e *MockClient_Expecter) DeleteSession(ctx interface{}, sessionToken interface{}) *MockClient_DeleteSession_Call {
	return &MockClient_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionToken)}
}

func (_c *MockClient_DeleteSession_Call) Run(run func(ctx context.Context, sessionToken string)) *MockClient_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DeleteSession_Call) Return(_a0 error) *MockClient_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// Ingest provides a mock function with given fields: ctx, sessionToken, in
func (_m *MockClient) Ingest(ctx context.Context, sessionToken string, in IngestInput) (IngestSummary, error) {
	ret := _m.Called(ctx, sessionToken, in)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 IngestSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, IngestInput) (IngestSummary, error)); ok {
		return rf(ctx, sessionToken, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, IngestInput) IngestSummary); ok {
		r0 = rf(ctx, sessionToken, in)
	} else {
		r0 = ret.Get(0).(IngestSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, IngestInput) error); ok {
		r1 = rf(ctx, sessionToken, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Ingest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ingest'
type MockClient_Ingest_Call struct {
	*mock.Call
}

// Ingest is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
//   - in IngestInput
func (_e *MockClient_Expecter) Ingest(ctx interface{}, sessionToken interface{}, in interface{}) *MockClient_Ingest_Call {
	return &MockClient_Ingest_Call{Call: _e.mock.On("Ingest", ctx, sessionToken, in)}
}

func (_c *MockClient_Ingest_Call) Run(run func(ctx context.Context, sessionToken string, in IngestInput)) *MockClient_Ingest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(IngestInput))
	})
	return _c
}

func (_c *MockClient_Ingest_Call) Return(_a0 IngestSummary, _a1 error) *MockClient_Ingest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Ingest_Call) RunAndReturn(run func(context.Context, string, IngestInput) (IngestSummary, error)) *MockClient_Ingest_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClient provides a mock function with given fields: ctx, name
func (_m *MockClient) RegisterClient(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockClient_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) RegisterClient(ctx interface{}, name interface{}) *MockClient_RegisterClient_Call {
	return &MockClient_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ctx, name)}
}

func (_c *MockClient_RegisterClient_Call) Run(run func(ctx context.Context, name string)) *MockClient_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_RegisterClient_Call) Return(created bool, err error) *MockClient_RegisterClient_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *MockClient_RegisterClient_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockClient_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, sessionToken, in
func (_m *MockClient) Search(ctx context.Context, sessionToken string, in SearchInput) (SearchResults, error) {
	ret := _m.Called(ctx, sessionToken, in)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 SearchResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchInput) (SearchResults, error)); ok {
		return rf(ctx, sessionToken, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchInput) SearchResults); ok {
		r0 = rf(ctx, sessionToken, in)
	} else {
		r0 = ret.Get(0).(SearchResults)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, SearchInput) error); ok {
		r1 = rf(ctx, sessionToken, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
//   - in SearchInput
func (_e *MockClient_Expecter) Search(ctx interface{}, sessionToken interface{}, in interface{}) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search", ctx, sessionToken, in)}
}

func (_c *MockClient_Search_Call) Run(run func(ctx context.Context, sessionToken string, in SearchInput)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(SearchInput))
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(_a0 SearchResults, _a1 error) *MockClient_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(context.Context, string, SearchInput) (SearchResults, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// WriteEvents provides a mock function with given fields: ctx, sessionToken, events
func (_m *MockClient) WriteEvents(ctx context.Context, sessionToken string, events []EventInput) error {
	ret := _m.Called(ctx, sessionToken, events)

	if len(ret) == 0 {
		panic("no return value specified for WriteEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []EventInput) error); ok {
		r0 = rf(ctx, sessionToken, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WriteEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteEvents'
type MockClient_WriteEvents_Call struct {
	*mock.Call
}

// WriteEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
//   - events []EventInput
func (_e *MockClient_Expecter) WriteEvents(ctx interface{}, sessionToken interface{}, events interface{}) *MockClient_WriteEvents_Call {
	return &MockClient_WriteEvents_Call{Call: _e.mock.On("WriteEvents", ctx, sessionToken, events)}
}

func (_c *MockClient_WriteEvents_Call) Run(run func(ctx context.Context, sessionToken string, events []EventInput)) *MockClient_WriteEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]EventInput))
	})
	return _c
}

func (_c *MockClient_WriteEvents_Call) Return(_a0 error) *MockClient_WriteEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WriteEvents_Call) RunAndReturn(run func(context.Context, string, []EventInput) error) *MockClient_WriteEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
