//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package middleware

import (
	context "context"

	session "github.com/one-harsh/calm/internal/session"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSessionResolver is an autogenerated mock type for the SessionResolver type
type MockSessionResolver struct {
	mock.Mock
}

type MockSessionResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionResolver) EXPECT() *MockSessionResolver_Expecter {
	return &MockSessionResolver_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function with given fields: ctx, namespace, sessionToken
func (_m *MockSessionResolver) Lookup(ctx context.Context, namespace string, sessionToken string) (session.SessionMetadata, error) {
	ret := _m.Called(ctx, namespace, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 session.SessionMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (session.SessionMetadata, error)); ok {
		return rf(ctx, namespace, sessionToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) session.SessionMetadata); ok {
		r0 = rf(ctx, namespace, sessionToken)
	} else {
		r0 = ret.Get(0).(session.SessionMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionResolver_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockSessionResolver_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionToken string
func (_e *MockSessionResolver_Expecter) Lookup(ctx interface{}, namespace interface{}, sessionToken interface{}) *MockSessionResolver_Lookup_Call {
	return &MockSessionResolver_Lookup_Call{Call: _e.mock.On("Lookup", ctx, namespace, sessionToken)}
}

func (_c *MockSessionResolver_Lookup_Call) Run(run func(ctx context.Context, namespace string, sessionToken string)) *MockSessionResolver_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSessionResolver_Lookup_Call) Return(_a0 session.SessionMetadata, _a1 error) *MockSessionResolver_Lookup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionResolver_Lookup_Call) RunAndReturn(run func(context.Context, string, string) (session.SessionMetadata, error)) *MockSessionResolver_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, namespace, sessionToken, lastActivity
func (_m *MockSessionResolver) Touch(ctx context.Context, namespace string, sessionToken string, lastActivity time.Time) error {
	ret := _m.Called(ctx, namespace, sessionToken, lastActivity)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, namespace, sessionToken, lastActivity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionResolver_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockSessionResolver_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionToken string
//   - lastActivity time.Time
func (_e *MockSessionResolver_Expecter) Touch(ctx interface{}, namespace interface{}, sessionToken interface{}, lastActivity interface{}) *MockSessionResolver_Touch_Call {
	return &MockSessionResolver_Touch_Call{Call: _e.mock.On("Touch", ctx, namespace, sessionToken, lastActivity)}
}

func (_c *MockSessionResolver_Touch_Call) Run(run func(ctx context.Context, namespace string, sessionToken string, lastActivity time.Time)) *MockSessionResolver_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSessionResolver_Touch_Call) Return(_a0 error) *MockSessionResolver_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionResolver_Touch_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockSessionResolver_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionResolver creates a new instance of MockSessionResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionResolver {
	mock := &MockSessionResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
