//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	db "github.com/one-harsh/calm/internal/db"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockexpirySource is an autogenerated mock type for the expirySource type
type MockexpirySource struct {
	mock.Mock
}

type MockexpirySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockexpirySource) EXPECT() *MockexpirySource_Expecter {
	return &MockexpirySource_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function with given fields: ctx, namespace, sessionID
func (_m *MockexpirySource) DeleteByID(ctx context.Context, namespace string, sessionID int64) (db.DeleteSessionResult, error) {
	ret := _m.Called(ctx, namespace, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 db.DeleteSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (db.DeleteSessionResult, error)); ok {
		return rf(ctx, namespace, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) db.DeleteSessionResult); ok {
		r0 = rf(ctx, namespace, sessionID)
	} else {
		r0 = ret.Get(0).(db.DeleteSessionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, namespace, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpirySource_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockexpirySource_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
func (_e *MockexpirySource_Expecter) DeleteByID(ctx interface{}, namespace interface{}, sessionID interface{}) *MockexpirySource_DeleteByID_Call {
	return &MockexpirySource_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, namespace, sessionID)}
}

func (_c *MockexpirySource_DeleteByID_Call) Run(run func(ctx context.Context, namespace string, sessionID int64)) *MockexpirySource_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockexpirySource_DeleteByID_Call) Return(_a0 db.DeleteSessionResult, _a1 error) *MockexpirySource_DeleteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpirySource_DeleteByID_Call) RunAndReturn(run func(context.Context, string, int64) (db.DeleteSessionResult, error)) *MockexpirySource_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// ScanExpired provides a mock function with given fields: ctx, now
func (_m *MockexpirySource) ScanExpired(ctx context.Context, now time.Time) ([]db.SessionRef, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ScanExpired")
	}

	var r0 []db.SessionRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]db.SessionRef, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []db.SessionRef); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SessionRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpirySource_ScanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanExpired'
type MockexpirySource_ScanExpired_Call struct {
	*mock.Call
}

// ScanExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockexpirySource_Expecter) ScanExpired(ctx interface{}, now interface{}) *MockexpirySource_ScanExpired_Call {
	return &MockexpirySource_ScanExpired_Call{Call: _e.mock.On("ScanExpired", ctx, now)}
}

func (_c *MockexpirySource_ScanExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockexpirySource_ScanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockexpirySource_ScanExpired_Call) Return(_a0 []db.SessionRef, _a1 error) *MockexpirySource_ScanExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpirySource_ScanExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]db.SessionRef, error)) *MockexpirySource_ScanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockexpirySource creates a new instance of MockexpirySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockexpirySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockexpirySource {
	mock := &MockexpirySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
