//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	db "github.com/one-harsh/calm/internal/db"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockexpirySource is an autogenerated mock type for the expirySource type
type MockexpirySource struct {
	mock.Mock
}

type MockexpirySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockexpirySource) EXPECT() *MockexpirySource_Expecter {
	return &MockexpirySource_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, namespace, id
func (_m *MockexpirySource) Delete(ctx context.Context, namespace string, id string) (db.DeleteSessionResult, error) {
	ret := _m.Called(ctx, namespace, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 db.DeleteSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.DeleteSessionResult, error)); ok {
		return rf(ctx, namespace, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.DeleteSessionResult); ok {
		r0 = rf(ctx, namespace, id)
	} else {
		r0 = ret.Get(0).(db.DeleteSessionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpirySource_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockexpirySource_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - id string
func (_e *MockexpirySource_Expecter) Delete(ctx interface{}, namespace interface{}, id interface{}) *MockexpirySource_Delete_Call {
	return &MockexpirySource_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, id)}
}

func (_c *MockexpirySource_Delete_Call) Run(run func(ctx context.Context, namespace string, id string)) *MockexpirySource_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockexpirySource_Delete_Call) Return(_a0 db.DeleteSessionResult, _a1 error) *MockexpirySource_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpirySource_Delete_Call) RunAndReturn(run func(context.Context, string, string) (db.DeleteSessionResult, error)) *MockexpirySource_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ScanExpired provides a mock function with given fields: ctx, now
func (_m *MockexpirySource) ScanExpired(ctx context.Context, now time.Time) ([]db.SessionRef, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ScanExpired")
	}

	var r0 []db.SessionRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]db.SessionRef, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []db.SessionRef); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SessionRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpirySource_ScanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanExpired'
type MockexpirySource_ScanExpired_Call struct {
	*mock.Call
}

// ScanExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockexpirySource_Expecter) ScanExpired(ctx interface{}, now interface{}) *MockexpirySource_ScanExpired_Call {
	return &MockexpirySource_ScanExpired_Call{Call: _e.mock.On("ScanExpired", ctx, now)}
}

func (_c *MockexpirySource_ScanExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockexpirySource_ScanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockexpirySource_ScanExpired_Call) Return(_a0 []db.SessionRef, _a1 error) *MockexpirySource_ScanExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpirySource_ScanExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]db.SessionRef, error)) *MockexpirySource_ScanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockexpirySource creates a new instance of MockexpirySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockexpirySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockexpirySource {
	mock := &MockexpirySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
