//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package secrets

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSecretReader is an autogenerated mock type for the SecretReader type
type MockSecretReader struct {
	mock.Mock
}

type MockSecretReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretReader) EXPECT() *MockSecretReader_Expecter {
	return &MockSecretReader_Expecter{mock: &_m.Mock}
}

// ReadSecret provides a mock function with given fields: ctx, secret
func (_m *MockSecretReader) ReadSecret(ctx context.Context, secret Secret) string {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for ReadSecret")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, Secret) string); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSecretReader_ReadSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSecret'
type MockSecretReader_ReadSecret_Call struct {
	*mock.Call
}

// ReadSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secret Secret
func (_e *MockSecretReader_Expecter) ReadSecret(ctx interface{}, secret interface{}) *MockSecretReader_ReadSecret_Call {
	return &MockSecretReader_ReadSecret_Call{Call: _e.mock.On("ReadSecret", ctx, secret)}
}

func (_c *MockSecretReader_ReadSecret_Call) Run(run func(ctx context.Context, secret Secret)) *MockSecretReader_ReadSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Secret))
	})
	return _c
}

func (_c *MockSecretReader_ReadSecret_Call) Return(_a0 string) *MockSecretReader_ReadSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretReader_ReadSecret_Call) RunAndReturn(run func(context.Context, Secret) string) *MockSecretReader_ReadSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretReader creates a new instance of MockSecretReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretReader {
	mock := &MockSecretReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
