//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package db

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockDAL is an autogenerated mock type for the DAL type
type MockDAL struct {
	mock.Mock
}

type MockDAL_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDAL) EXPECT() *MockDAL_Expecter {
	return &MockDAL_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDAL) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDAL_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDAL_Expecter) Close() *MockDAL_Close_Call {
	return &MockDAL_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDAL_Close_Call) Run(run func()) *MockDAL_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDAL_Close_Call) Return(_a0 error) *MockDAL_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_Close_Call) RunAndReturn(run func() error) *MockDAL_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CountClientSessions provides a mock function with given fields: ctx, namespace, name
func (_m *MockDAL) CountClientSessions(ctx context.Context, namespace string, name string) (int, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for CountClientSessions")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_CountClientSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountClientSessions'
type MockDAL_CountClientSessions_Call struct {
	*mock.Call
}

// CountClientSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockDAL_Expecter) CountClientSessions(ctx interface{}, namespace interface{}, name interface{}) *MockDAL_CountClientSessions_Call {
	return &MockDAL_CountClientSessions_Call{Call: _e.mock.On("CountClientSessions", ctx, namespace, name)}
}

func (_c *MockDAL_CountClientSessions_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockDAL_CountClientSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDAL_CountClientSessions_Call) Return(_a0 int, _a1 error) *MockDAL_CountClientSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_CountClientSessions_Call) RunAndReturn(run func(context.Context, string, string) (int, error)) *MockDAL_CountClientSessions_Call {
	_c.Call.Return(run)
	return _c
}

// CountSessions provides a mock function with given fields: ctx, filter
func (_m *MockDAL) CountSessions(ctx context.Context, filter ListSessionsFilter) (int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountSessions")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) (int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) int); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_CountSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSessions'
type MockDAL_CountSessions_Call struct {
	*mock.Call
}

// CountSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockDAL_Expecter) CountSessions(ctx interface{}, filter interface{}) *MockDAL_CountSessions_Call {
	return &MockDAL_CountSessions_Call{Call: _e.mock.On("CountSessions", ctx, filter)}
}

func (_c *MockDAL_CountSessions_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockDAL_CountSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockDAL_CountSessions_Call) Return(_a0 int, _a1 error) *MockDAL_CountSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_CountSessions_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) (int, error)) *MockDAL_CountSessions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, s
func (_m *MockDAL) CreateSession(ctx context.Context, s Session) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Session) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockDAL_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - s Session
func (_e *MockDAL_Expecter) CreateSession(ctx interface{}, s interface{}) *MockDAL_CreateSession_Call {
	return &MockDAL_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, s)}
}

func (_c *MockDAL_CreateSession_Call) Run(run func(ctx context.Context, s Session)) *MockDAL_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Session))
	})
	return _c
}

func (_c *MockDAL_CreateSession_Call) Return(_a0 error) *MockDAL_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_CreateSession_Call) RunAndReturn(run func(context.Context, Session) error) *MockDAL_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function with given fields: ctx, namespace, name
func (_m *MockDAL) DeleteClient(ctx context.Context, namespace string, name string) (DeleteClientResult, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 DeleteClientResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (DeleteClientResult, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) DeleteClientResult); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(DeleteClientResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockDAL_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockDAL_Expecter) DeleteClient(ctx interface{}, namespace interface{}, name interface{}) *MockDAL_DeleteClient_Call {
	return &MockDAL_DeleteClient_Call{Call: _e.mock.On("DeleteClient", ctx, namespace, name)}
}

func (_c *MockDAL_DeleteClient_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockDAL_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDAL_DeleteClient_Call) Return(_a0 DeleteClientResult, _a1 error) *MockDAL_DeleteClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_DeleteClient_Call) RunAndReturn(run func(context.Context, string, string) (DeleteClientResult, error)) *MockDAL_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, id
func (_m *MockDAL) DeleteSession(ctx context.Context, id string) (DeleteSessionResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 DeleteSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (DeleteSessionResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) DeleteSessionResult); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(DeleteSessionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockDAL_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDAL_Expecter) DeleteSession(ctx interface{}, id interface{}) *MockDAL_DeleteSession_Call {
	return &MockDAL_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, id)}
}

func (_c *MockDAL_DeleteSession_Call) Run(run func(ctx context.Context, id string)) *MockDAL_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDAL_DeleteSession_Call) Return(_a0 DeleteSessionResult, _a1 error) *MockDAL_DeleteSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_DeleteSession_Call) RunAndReturn(run func(context.Context, string) (DeleteSessionResult, error)) *MockDAL_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessions provides a mock function with given fields: ctx, filter
func (_m *MockDAL) DeleteSessions(ctx context.Context, filter ListSessionsFilter) (DeleteSessionsResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessions")
	}

	var r0 DeleteSessionsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) (DeleteSessionsResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) DeleteSessionsResult); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(DeleteSessionsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_DeleteSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessions'
type MockDAL_DeleteSessions_Call struct {
	*mock.Call
}

// DeleteSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockDAL_Expecter) DeleteSessions(ctx interface{}, filter interface{}) *MockDAL_DeleteSessions_Call {
	return &MockDAL_DeleteSessions_Call{Call: _e.mock.On("DeleteSessions", ctx, filter)}
}

func (_c *MockDAL_DeleteSessions_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockDAL_DeleteSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockDAL_DeleteSessions_Call) Return(_a0 DeleteSessionsResult, _a1 error) *MockDAL_DeleteSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_DeleteSessions_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) (DeleteSessionsResult, error)) *MockDAL_DeleteSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *MockDAL) GetSession(ctx context.Context, id string) (Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Session); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockDAL_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDAL_Expecter) GetSession(ctx interface{}, id interface{}) *MockDAL_GetSession_Call {
	return &MockDAL_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockDAL_GetSession_Call) Run(run func(ctx context.Context, id string)) *MockDAL_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDAL_GetSession_Call) Return(_a0 Session, _a1 error) *MockDAL_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_GetSession_Call) RunAndReturn(run func(context.Context, string) (Session, error)) *MockDAL_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: ctx, in
func (_m *MockDAL) Index(ctx context.Context, in IndexInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, IndexInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockDAL_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - in IndexInput
func (_e *MockDAL_Expecter) Index(ctx interface{}, in interface{}) *MockDAL_Index_Call {
	return &MockDAL_Index_Call{Call: _e.mock.On("Index", ctx, in)}
}

func (_c *MockDAL_Index_Call) Run(run func(ctx context.Context, in IndexInput)) *MockDAL_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(IndexInput))
	})
	return _c
}

func (_c *MockDAL_Index_Call) Return(_a0 error) *MockDAL_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_Index_Call) RunAndReturn(run func(context.Context, IndexInput) error) *MockDAL_Index_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function with given fields: ctx, namespace
func (_m *MockDAL) ListClients(ctx context.Context, namespace string) ([]ClientSummary, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []ClientSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]ClientSummary, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []ClientSummary); ok {
		r0 = rf(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ClientSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockDAL_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockDAL_Expecter) ListClients(ctx interface{}, namespace interface{}) *MockDAL_ListClients_Call {
	return &MockDAL_ListClients_Call{Call: _e.mock.On("ListClients", ctx, namespace)}
}

func (_c *MockDAL_ListClients_Call) Run(run func(ctx context.Context, namespace string)) *MockDAL_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDAL_ListClients_Call) Return(_a0 []ClientSummary, _a1 error) *MockDAL_ListClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_ListClients_Call) RunAndReturn(run func(context.Context, string) ([]ClientSummary, error)) *MockDAL_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagedSessions provides a mock function with given fields: ctx, filter
func (_m *MockDAL) ListManagedSessions(ctx context.Context, filter ListSessionsFilter) ([]ManagedSession, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListManagedSessions")
	}

	var r0 []ManagedSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) ([]ManagedSession, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) []ManagedSession); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ManagedSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_ListManagedSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagedSessions'
type MockDAL_ListManagedSessions_Call struct {
	*mock.Call
}

// ListManagedSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockDAL_Expecter) ListManagedSessions(ctx interface{}, filter interface{}) *MockDAL_ListManagedSessions_Call {
	return &MockDAL_ListManagedSessions_Call{Call: _e.mock.On("ListManagedSessions", ctx, filter)}
}

func (_c *MockDAL_ListManagedSessions_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockDAL_ListManagedSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockDAL_ListManagedSessions_Call) Return(_a0 []ManagedSession, _a1 error) *MockDAL_ListManagedSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_ListManagedSessions_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) ([]ManagedSession, error)) *MockDAL_ListManagedSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListSources provides a mock function with given fields: ctx, sessionID
func (_m *MockDAL) ListSources(ctx context.Context, sessionID string) ([]SourceSummary, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSources")
	}

	var r0 []SourceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]SourceSummary, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []SourceSummary); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SourceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_ListSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSources'
type MockDAL_ListSources_Call struct {
	*mock.Call
}

// ListSources is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockDAL_Expecter) ListSources(ctx interface{}, sessionID interface{}) *MockDAL_ListSources_Call {
	return &MockDAL_ListSources_Call{Call: _e.mock.On("ListSources", ctx, sessionID)}
}

func (_c *MockDAL_ListSources_Call) Run(run func(ctx context.Context, sessionID string)) *MockDAL_ListSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDAL_ListSources_Call) Return(_a0 []SourceSummary, _a1 error) *MockDAL_ListSources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_ListSources_Call) RunAndReturn(run func(context.Context, string) ([]SourceSummary, error)) *MockDAL_ListSources_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEvents provides a mock function with given fields: ctx, sessionID, filter
func (_m *MockDAL) ReadEvents(ctx context.Context, sessionID string, filter EventFilter) ([]Event, error) {
	ret := _m.Called(ctx, sessionID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ReadEvents")
	}

	var r0 []Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, EventFilter) ([]Event, error)); ok {
		return rf(ctx, sessionID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, EventFilter) []Event); ok {
		r0 = rf(ctx, sessionID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, EventFilter) error); ok {
		r1 = rf(ctx, sessionID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_ReadEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEvents'
type MockDAL_ReadEvents_Call struct {
	*mock.Call
}

// ReadEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - filter EventFilter
func (_e *MockDAL_Expecter) ReadEvents(ctx interface{}, sessionID interface{}, filter interface{}) *MockDAL_ReadEvents_Call {
	return &MockDAL_ReadEvents_Call{Call: _e.mock.On("ReadEvents", ctx, sessionID, filter)}
}

func (_c *MockDAL_ReadEvents_Call) Run(run func(ctx context.Context, sessionID string, filter EventFilter)) *MockDAL_ReadEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(EventFilter))
	})
	return _c
}

func (_c *MockDAL_ReadEvents_Call) Return(_a0 []Event, _a1 error) *MockDAL_ReadEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_ReadEvents_Call) RunAndReturn(run func(context.Context, string, EventFilter) ([]Event, error)) *MockDAL_ReadEvents_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClient provides a mock function with given fields: ctx, namespace, name
func (_m *MockDAL) RegisterClient(ctx context.Context, namespace string, name string) error {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockDAL_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockDAL_Expecter) RegisterClient(ctx interface{}, namespace interface{}, name interface{}) *MockDAL_RegisterClient_Call {
	return &MockDAL_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ctx, namespace, name)}
}

func (_c *MockDAL_RegisterClient_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockDAL_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDAL_RegisterClient_Call) Return(_a0 error) *MockDAL_RegisterClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_RegisterClient_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDAL_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}

// ScanExpiredSessions provides a mock function with given fields: ctx, now
func (_m *MockDAL) ScanExpiredSessions(ctx context.Context, now time.Time) ([]string, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ScanExpiredSessions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]string, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []string); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_ScanExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanExpiredSessions'
type MockDAL_ScanExpiredSessions_Call struct {
	*mock.Call
}

// ScanExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockDAL_Expecter) ScanExpiredSessions(ctx interface{}, now interface{}) *MockDAL_ScanExpiredSessions_Call {
	return &MockDAL_ScanExpiredSessions_Call{Call: _e.mock.On("ScanExpiredSessions", ctx, now)}
}

func (_c *MockDAL_ScanExpiredSessions_Call) Run(run func(ctx context.Context, now time.Time)) *MockDAL_ScanExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockDAL_ScanExpiredSessions_Call) Return(_a0 []string, _a1 error) *MockDAL_ScanExpiredSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_ScanExpiredSessions_Call) RunAndReturn(run func(context.Context, time.Time) ([]string, error)) *MockDAL_ScanExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, in
func (_m *MockDAL) Search(ctx context.Context, in SearchInput) ([]SearchResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, SearchInput) ([]SearchResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, SearchInput) []SearchResult); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, SearchInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockDAL_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - in SearchInput
func (_e *MockDAL_Expecter) Search(ctx interface{}, in interface{}) *MockDAL_Search_Call {
	return &MockDAL_Search_Call{Call: _e.mock.On("Search", ctx, in)}
}

func (_c *MockDAL_Search_Call) Run(run func(ctx context.Context, in SearchInput)) *MockDAL_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(SearchInput))
	})
	return _c
}

func (_c *MockDAL_Search_Call) Return(_a0 []SearchResult, _a1 error) *MockDAL_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_Search_Call) RunAndReturn(run func(context.Context, SearchInput) ([]SearchResult, error)) *MockDAL_Search_Call {
	_c.Call.Return(run)
	return _c
}

// TouchSession provides a mock function with given fields: ctx, id, lastActivity
func (_m *MockDAL) TouchSession(ctx context.Context, id string, lastActivity time.Time) error {
	ret := _m.Called(ctx, id, lastActivity)

	if len(ret) == 0 {
		panic("no return value specified for TouchSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, lastActivity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_TouchSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchSession'
type MockDAL_TouchSession_Call struct {
	*mock.Call
}

// TouchSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - lastActivity time.Time
func (_e *MockDAL_Expecter) TouchSession(ctx interface{}, id interface{}, lastActivity interface{}) *MockDAL_TouchSession_Call {
	return &MockDAL_TouchSession_Call{Call: _e.mock.On("TouchSession", ctx, id, lastActivity)}
}

func (_c *MockDAL_TouchSession_Call) Run(run func(ctx context.Context, id string, lastActivity time.Time)) *MockDAL_TouchSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDAL_TouchSession_Call) Return(_a0 error) *MockDAL_TouchSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_TouchSession_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockDAL_TouchSession_Call {
	_c.Call.Return(run)
	return _c
}

// WriteEvents provides a mock function with given fields: ctx, sessionID, events
func (_m *MockDAL) WriteEvents(ctx context.Context, sessionID string, events []Event) (int, error) {
	ret := _m.Called(ctx, sessionID, events)

	if len(ret) == 0 {
		panic("no return value specified for WriteEvents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []Event) (int, error)); ok {
		return rf(ctx, sessionID, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []Event) int); ok {
		r0 = rf(ctx, sessionID, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []Event) error); ok {
		r1 = rf(ctx, sessionID, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAL_WriteEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteEvents'
type MockDAL_WriteEvents_Call struct {
	*mock.Call
}

// WriteEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - events []Event
func (_e *MockDAL_Expecter) WriteEvents(ctx interface{}, sessionID interface{}, events interface{}) *MockDAL_WriteEvents_Call {
	return &MockDAL_WriteEvents_Call{Call: _e.mock.On("WriteEvents", ctx, sessionID, events)}
}

func (_c *MockDAL_WriteEvents_Call) Run(run func(ctx context.Context, sessionID string, events []Event)) *MockDAL_WriteEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]Event))
	})
	return _c
}

func (_c *MockDAL_WriteEvents_Call) Return(_a0 int, _a1 error) *MockDAL_WriteEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAL_WriteEvents_Call) RunAndReturn(run func(context.Context, string, []Event) (int, error)) *MockDAL_WriteEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDAL creates a new instance of MockDAL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDAL(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDAL {
	mock := &MockDAL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
