//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSourcesRepo is an autogenerated mock type for the SourcesRepo type
type MockSourcesRepo struct {
	mock.Mock
}

type MockSourcesRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourcesRepo) EXPECT() *MockSourcesRepo_Expecter {
	return &MockSourcesRepo_Expecter{mock: &_m.Mock}
}

// Index provides a mock function with given fields: ctx, namespace, in
func (_m *MockSourcesRepo) Index(ctx context.Context, namespace string, in IndexInput) (bool, error) {
	ret := _m.Called(ctx, namespace, in)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, IndexInput) (bool, error)); ok {
		return rf(ctx, namespace, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, IndexInput) bool); ok {
		r0 = rf(ctx, namespace, in)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, IndexInput) error); ok {
		r1 = rf(ctx, namespace, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourcesRepo_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockSourcesRepo_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - in IndexInput
func (_e *MockSourcesRepo_Expecter) Index(ctx interface{}, namespace interface{}, in interface{}) *MockSourcesRepo_Index_Call {
	return &MockSourcesRepo_Index_Call{Call: _e.mock.On("Index", ctx, namespace, in)}
}

func (_c *MockSourcesRepo_Index_Call) Run(run func(ctx context.Context, namespace string, in IndexInput)) *MockSourcesRepo_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(IndexInput))
	})
	return _c
}

func (_c *MockSourcesRepo_Index_Call) Return(created bool, err error) *MockSourcesRepo_Index_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *MockSourcesRepo_Index_Call) RunAndReturn(run func(context.Context, string, IndexInput) (bool, error)) *MockSourcesRepo_Index_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, namespace, sessionID
func (_m *MockSourcesRepo) List(ctx context.Context, namespace string, sessionID int64) ([]SourceSummary, error) {
	ret := _m.Called(ctx, namespace, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []SourceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]SourceSummary, error)); ok {
		return rf(ctx, namespace, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []SourceSummary); ok {
		r0 = rf(ctx, namespace, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SourceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, namespace, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourcesRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSourcesRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
func (_e *MockSourcesRepo_Expecter) List(ctx interface{}, namespace interface{}, sessionID interface{}) *MockSourcesRepo_List_Call {
	return &MockSourcesRepo_List_Call{Call: _e.mock.On("List", ctx, namespace, sessionID)}
}

func (_c *MockSourcesRepo_List_Call) Run(run func(ctx context.Context, namespace string, sessionID int64)) *MockSourcesRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockSourcesRepo_List_Call) Return(_a0 []SourceSummary, _a1 error) *MockSourcesRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourcesRepo_List_Call) RunAndReturn(run func(context.Context, string, int64) ([]SourceSummary, error)) *MockSourcesRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, namespace, in
func (_m *MockSourcesRepo) Search(ctx context.Context, namespace string, in SearchInput) ([]SearchResult, error) {
	ret := _m.Called(ctx, namespace, in)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchInput) ([]SearchResult, error)); ok {
		return rf(ctx, namespace, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchInput) []SearchResult); ok {
		r0 = rf(ctx, namespace, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, SearchInput) error); ok {
		r1 = rf(ctx, namespace, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourcesRepo_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSourcesRepo_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - in SearchInput
func (_e *MockSourcesRepo_Expecter) Search(ctx interface{}, namespace interface{}, in interface{}) *MockSourcesRepo_Search_Call {
	return &MockSourcesRepo_Search_Call{Call: _e.mock.On("Search", ctx, namespace, in)}
}

func (_c *MockSourcesRepo_Search_Call) Run(run func(ctx context.Context, namespace string, in SearchInput)) *MockSourcesRepo_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(SearchInput))
	})
	return _c
}

func (_c *MockSourcesRepo_Search_Call) Return(_a0 []SearchResult, _a1 error) *MockSourcesRepo_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourcesRepo_Search_Call) RunAndReturn(run func(context.Context, string, SearchInput) ([]SearchResult, error)) *MockSourcesRepo_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourcesRepo creates a new instance of MockSourcesRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourcesRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourcesRepo {
	mock := &MockSourcesRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
