//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClientRepo is an autogenerated mock type for the ClientRepo type
type MockClientRepo struct {
	mock.Mock
}

type MockClientRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepo) EXPECT() *MockClientRepo_Expecter {
	return &MockClientRepo_Expecter{mock: &_m.Mock}
}

// CountSessions provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientRepo) CountSessions(ctx context.Context, namespace string, name string) (int, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for CountSessions")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepo_CountSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSessions'
type MockClientRepo_CountSessions_Call struct {
	*mock.Call
}

// CountSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockClientRepo_Expecter) CountSessions(ctx interface{}, namespace interface{}, name interface{}) *MockClientRepo_CountSessions_Call {
	return &MockClientRepo_CountSessions_Call{Call: _e.mock.On("CountSessions", ctx, namespace, name)}
}

func (_c *MockClientRepo_CountSessions_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockClientRepo_CountSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientRepo_CountSessions_Call) Return(_a0 int, _a1 error) *MockClientRepo_CountSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepo_CountSessions_Call) RunAndReturn(run func(context.Context, string, string) (int, error)) *MockClientRepo_CountSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientRepo) Delete(ctx context.Context, namespace string, name string) (DeleteClientResult, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 DeleteClientResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (DeleteClientResult, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) DeleteClientResult); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(DeleteClientResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClientRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockClientRepo_Expecter) Delete(ctx interface{}, namespace interface{}, name interface{}) *MockClientRepo_Delete_Call {
	return &MockClientRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, name)}
}

func (_c *MockClientRepo_Delete_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockClientRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientRepo_Delete_Call) Return(_a0 DeleteClientResult, _a1 error) *MockClientRepo_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepo_Delete_Call) RunAndReturn(run func(context.Context, string, string) (DeleteClientResult, error)) *MockClientRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, namespace
func (_m *MockClientRepo) List(ctx context.Context, namespace string) ([]ClientSummary, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ClientSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]ClientSummary, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []ClientSummary); ok {
		r0 = rf(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ClientSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockClientRepo_Expecter) List(ctx interface{}, namespace interface{}) *MockClientRepo_List_Call {
	return &MockClientRepo_List_Call{Call: _e.mock.On("List", ctx, namespace)}
}

func (_c *MockClientRepo_List_Call) Run(run func(ctx context.Context, namespace string)) *MockClientRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientRepo_List_Call) Return(_a0 []ClientSummary, _a1 error) *MockClientRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepo_List_Call) RunAndReturn(run func(context.Context, string) ([]ClientSummary, error)) *MockClientRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// LookupByToken provides a mock function with given fields: ctx, namespace, tokenHash
func (_m *MockClientRepo) LookupByToken(ctx context.Context, namespace string, tokenHash []byte) (string, error) {
	ret := _m.Called(ctx, namespace, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for LookupByToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, namespace, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, namespace, tokenHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, namespace, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepo_LookupByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupByToken'
type MockClientRepo_LookupByToken_Call struct {
	*mock.Call
}

// LookupByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - tokenHash []byte
func (_e *MockClientRepo_Expecter) LookupByToken(ctx interface{}, namespace interface{}, tokenHash interface{}) *MockClientRepo_LookupByToken_Call {
	return &MockClientRepo_LookupByToken_Call{Call: _e.mock.On("LookupByToken", ctx, namespace, tokenHash)}
}

func (_c *MockClientRepo_LookupByToken_Call) Run(run func(ctx context.Context, namespace string, tokenHash []byte)) *MockClientRepo_LookupByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockClientRepo_LookupByToken_Call) Return(name string, err error) *MockClientRepo_LookupByToken_Call {
	_c.Call.Return(name, err)
	return _c
}

func (_c *MockClientRepo_LookupByToken_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *MockClientRepo_LookupByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientRepo) Register(ctx context.Context, namespace string, name string) (bool, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepo_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockClientRepo_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockClientRepo_Expecter) Register(ctx interface{}, namespace interface{}, name interface{}) *MockClientRepo_Register_Call {
	return &MockClientRepo_Register_Call{Call: _e.mock.On("Register", ctx, namespace, name)}
}

func (_c *MockClientRepo_Register_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockClientRepo_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientRepo_Register_Call) Return(created bool, err error) *MockClientRepo_Register_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *MockClientRepo_Register_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockClientRepo_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterWithCredential provides a mock function with given fields: ctx, namespace, name, tokenHash
func (_m *MockClientRepo) RegisterWithCredential(ctx context.Context, namespace string, name string, tokenHash []byte) error {
	ret := _m.Called(ctx, namespace, name, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWithCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, namespace, name, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepo_RegisterWithCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWithCredential'
type MockClientRepo_RegisterWithCredential_Call struct {
	*mock.Call
}

// RegisterWithCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - tokenHash []byte
func (_e *MockClientRepo_Expecter) RegisterWithCredential(ctx interface{}, namespace interface{}, name interface{}, tokenHash interface{}) *MockClientRepo_RegisterWithCredential_Call {
	return &MockClientRepo_RegisterWithCredential_Call{Call: _e.mock.On("RegisterWithCredential", ctx, namespace, name, tokenHash)}
}

func (_c *MockClientRepo_RegisterWithCredential_Call) Run(run func(ctx context.Context, namespace string, name string, tokenHash []byte)) *MockClientRepo_RegisterWithCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockClientRepo_RegisterWithCredential_Call) Return(_a0 error) *MockClientRepo_RegisterWithCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepo_RegisterWithCredential_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockClientRepo_RegisterWithCredential_Call {
	_c.Call.Return(run)
	return _c
}

// RotateCredential provides a mock function with given fields: ctx, namespace, name, newHash
func (_m *MockClientRepo) RotateCredential(ctx context.Context, namespace string, name string, newHash []byte) error {
	ret := _m.Called(ctx, namespace, name, newHash)

	if len(ret) == 0 {
		panic("no return value specified for RotateCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, namespace, name, newHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepo_RotateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateCredential'
type MockClientRepo_RotateCredential_Call struct {
	*mock.Call
}

// RotateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - newHash []byte
func (_e *MockClientRepo_Expecter) RotateCredential(ctx interface{}, namespace interface{}, name interface{}, newHash interface{}) *MockClientRepo_RotateCredential_Call {
	return &MockClientRepo_RotateCredential_Call{Call: _e.mock.On("RotateCredential", ctx, namespace, name, newHash)}
}

func (_c *MockClientRepo_RotateCredential_Call) Run(run func(ctx context.Context, namespace string, name string, newHash []byte)) *MockClientRepo_RotateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockClientRepo_RotateCredential_Call) Return(_a0 error) *MockClientRepo_RotateCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepo_RotateCredential_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockClientRepo_RotateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientRepo creates a new instance of MockClientRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepo {
	mock := &MockClientRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
