//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventsRepo is an autogenerated mock type for the EventsRepo type
type MockEventsRepo struct {
	mock.Mock
}

type MockEventsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsRepo) EXPECT() *MockEventsRepo_Expecter {
	return &MockEventsRepo_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: ctx, namespace, sessionID, filter
func (_m *MockEventsRepo) Read(ctx context.Context, namespace string, sessionID int64, filter EventFilter) ([]Event, error) {
	ret := _m.Called(ctx, namespace, sessionID, filter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, EventFilter) ([]Event, error)); ok {
		return rf(ctx, namespace, sessionID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, EventFilter) []Event); ok {
		r0 = rf(ctx, namespace, sessionID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, EventFilter) error); ok {
		r1 = rf(ctx, namespace, sessionID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventsRepo_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockEventsRepo_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
//   - filter EventFilter
func (_e *MockEventsRepo_Expecter) Read(ctx interface{}, namespace interface{}, sessionID interface{}, filter interface{}) *MockEventsRepo_Read_Call {
	return &MockEventsRepo_Read_Call{Call: _e.mock.On("Read", ctx, namespace, sessionID, filter)}
}

func (_c *MockEventsRepo_Read_Call) Run(run func(ctx context.Context, namespace string, sessionID int64, filter EventFilter)) *MockEventsRepo_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(EventFilter))
	})
	return _c
}

func (_c *MockEventsRepo_Read_Call) Return(_a0 []Event, _a1 error) *MockEventsRepo_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventsRepo_Read_Call) RunAndReturn(run func(context.Context, string, int64, EventFilter) ([]Event, error)) *MockEventsRepo_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function with given fields: ctx, namespace, sessionID
func (_m *MockEventsRepo) Snapshot(ctx context.Context, namespace string, sessionID int64) ([]Event, error) {
	ret := _m.Called(ctx, namespace, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 []Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]Event, error)); ok {
		return rf(ctx, namespace, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []Event); ok {
		r0 = rf(ctx, namespace, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, namespace, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventsRepo_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockEventsRepo_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
func (_e *MockEventsRepo_Expecter) Snapshot(ctx interface{}, namespace interface{}, sessionID interface{}) *MockEventsRepo_Snapshot_Call {
	return &MockEventsRepo_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx, namespace, sessionID)}
}

func (_c *MockEventsRepo_Snapshot_Call) Run(run func(ctx context.Context, namespace string, sessionID int64)) *MockEventsRepo_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockEventsRepo_Snapshot_Call) Return(_a0 []Event, _a1 error) *MockEventsRepo_Snapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventsRepo_Snapshot_Call) RunAndReturn(run func(context.Context, string, int64) ([]Event, error)) *MockEventsRepo_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: ctx, namespace, sessionID, events
func (_m *MockEventsRepo) Write(ctx context.Context, namespace string, sessionID int64, events []EventInput) (int, error) {
	ret := _m.Called(ctx, namespace, sessionID, events)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, []EventInput) (int, error)); ok {
		return rf(ctx, namespace, sessionID, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, []EventInput) int); ok {
		r0 = rf(ctx, namespace, sessionID, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, []EventInput) error); ok {
		r1 = rf(ctx, namespace, sessionID, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventsRepo_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockEventsRepo_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
//   - events []EventInput
func (_e *MockEventsRepo_Expecter) Write(ctx interface{}, namespace interface{}, sessionID interface{}, events interface{}) *MockEventsRepo_Write_Call {
	return &MockEventsRepo_Write_Call{Call: _e.mock.On("Write", ctx, namespace, sessionID, events)}
}

func (_c *MockEventsRepo_Write_Call) Run(run func(ctx context.Context, namespace string, sessionID int64, events []EventInput)) *MockEventsRepo_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].([]EventInput))
	})
	return _c
}

func (_c *MockEventsRepo_Write_Call) Return(accepted int, err error) *MockEventsRepo_Write_Call {
	_c.Call.Return(accepted, err)
	return _c
}

func (_c *MockEventsRepo_Write_Call) RunAndReturn(run func(context.Context, string, int64, []EventInput) (int, error)) *MockEventsRepo_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventsRepo creates a new instance of MockEventsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsRepo {
	mock := &MockEventsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
