//go:build mocks
// +build mocks

// Code generated by mockery v2.53.6. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDAL is an autogenerated mock type for the DAL type
type MockDAL struct {
	mock.Mock
}

type MockDAL_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDAL) EXPECT() *MockDAL_Expecter {
	return &MockDAL_Expecter{mock: &_m.Mock}
}

// Clients provides a mock function with no fields
func (_m *MockDAL) Clients() ClientRepo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clients")
	}

	var r0 ClientRepo
	if rf, ok := ret.Get(0).(func() ClientRepo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientRepo)
		}
	}

	return r0
}

// MockDAL_Clients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clients'
type MockDAL_Clients_Call struct {
	*mock.Call
}

// Clients is a helper method to define mock.On call
func (_e *MockDAL_Expecter) Clients() *MockDAL_Clients_Call {
	return &MockDAL_Clients_Call{Call: _e.mock.On("Clients")}
}

func (_c *MockDAL_Clients_Call) Run(run func()) *MockDAL_Clients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDAL_Clients_Call) Return(_a0 ClientRepo) *MockDAL_Clients_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_Clients_Call) RunAndReturn(run func() ClientRepo) *MockDAL_Clients_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with no fields
func (_m *MockDAL) Events() EventsRepo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 EventsRepo
	if rf, ok := ret.Get(0).(func() EventsRepo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventsRepo)
		}
	}

	return r0
}

// MockDAL_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockDAL_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *MockDAL_Expecter) Events() *MockDAL_Events_Call {
	return &MockDAL_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *MockDAL_Events_Call) Run(run func()) *MockDAL_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDAL_Events_Call) Return(_a0 EventsRepo) *MockDAL_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_Events_Call) RunAndReturn(run func() EventsRepo) *MockDAL_Events_Call {
	_c.Call.Return(run)
	return _c
}

// Sessions provides a mock function with no fields
func (_m *MockDAL) Sessions() SessionRepo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sessions")
	}

	var r0 SessionRepo
	if rf, ok := ret.Get(0).(func() SessionRepo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SessionRepo)
		}
	}

	return r0
}

// MockDAL_Sessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sessions'
type MockDAL_Sessions_Call struct {
	*mock.Call
}

// Sessions is a helper method to define mock.On call
func (_e *MockDAL_Expecter) Sessions() *MockDAL_Sessions_Call {
	return &MockDAL_Sessions_Call{Call: _e.mock.On("Sessions")}
}

func (_c *MockDAL_Sessions_Call) Run(run func()) *MockDAL_Sessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDAL_Sessions_Call) Return(_a0 SessionRepo) *MockDAL_Sessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_Sessions_Call) RunAndReturn(run func() SessionRepo) *MockDAL_Sessions_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *MockDAL) WithTx(ctx context.Context, fn func(Repos) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(Repos) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDAL_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockDAL_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(Repos) error
func (_e *MockDAL_Expecter) WithTx(ctx interface{}, fn interface{}) *MockDAL_WithTx_Call {
	return &MockDAL_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockDAL_WithTx_Call) Run(run func(ctx context.Context, fn func(Repos) error)) *MockDAL_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(Repos) error))
	})
	return _c
}

func (_c *MockDAL_WithTx_Call) Return(_a0 error) *MockDAL_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDAL_WithTx_Call) RunAndReturn(run func(context.Context, func(Repos) error) error) *MockDAL_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDAL creates a new instance of MockDAL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDAL(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDAL {
	mock := &MockDAL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
