//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockChunksRepo is an autogenerated mock type for the ChunksRepo type
type MockChunksRepo struct {
	mock.Mock
}

type MockChunksRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunksRepo) EXPECT() *MockChunksRepo_Expecter {
	return &MockChunksRepo_Expecter{mock: &_m.Mock}
}

// DeleteForSource provides a mock function with given fields: ctx, sourceID
func (_m *MockChunksRepo) DeleteForSource(ctx context.Context, sourceID int64) error {
	ret := _m.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForSource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunksRepo_DeleteForSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteForSource'
type MockChunksRepo_DeleteForSource_Call struct {
	*mock.Call
}

// DeleteForSource is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID int64
func (_e *MockChunksRepo_Expecter) DeleteForSource(ctx interface{}, sourceID interface{}) *MockChunksRepo_DeleteForSource_Call {
	return &MockChunksRepo_DeleteForSource_Call{Call: _e.mock.On("DeleteForSource", ctx, sourceID)}
}

func (_c *MockChunksRepo_DeleteForSource_Call) Run(run func(ctx context.Context, sourceID int64)) *MockChunksRepo_DeleteForSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockChunksRepo_DeleteForSource_Call) Return(_a0 error) *MockChunksRepo_DeleteForSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunksRepo_DeleteForSource_Call) RunAndReturn(run func(context.Context, int64) error) *MockChunksRepo_DeleteForSource_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, sourceID, chunks
func (_m *MockChunksRepo) Insert(ctx context.Context, sourceID int64, chunks []Chunk) error {
	ret := _m.Called(ctx, sourceID, chunks)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []Chunk) error); ok {
		r0 = rf(ctx, sourceID, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunksRepo_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockChunksRepo_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID int64
//   - chunks []Chunk
func (_e *MockChunksRepo_Expecter) Insert(ctx interface{}, sourceID interface{}, chunks interface{}) *MockChunksRepo_Insert_Call {
	return &MockChunksRepo_Insert_Call{Call: _e.mock.On("Insert", ctx, sourceID, chunks)}
}

func (_c *MockChunksRepo_Insert_Call) Run(run func(ctx context.Context, sourceID int64, chunks []Chunk)) *MockChunksRepo_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]Chunk))
	})
	return _c
}

func (_c *MockChunksRepo_Insert_Call) Return(_a0 error) *MockChunksRepo_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunksRepo_Insert_Call) RunAndReturn(run func(context.Context, int64, []Chunk) error) *MockChunksRepo_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunksRepo creates a new instance of MockChunksRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunksRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunksRepo {
	mock := &MockChunksRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
