//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVocabularyRepo is an autogenerated mock type for the VocabularyRepo type
type MockVocabularyRepo struct {
	mock.Mock
}

type MockVocabularyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVocabularyRepo) EXPECT() *MockVocabularyRepo_Expecter {
	return &MockVocabularyRepo_Expecter{mock: &_m.Mock}
}

// DecrementForSource provides a mock function with given fields: ctx, sourceID
func (_m *MockVocabularyRepo) DecrementForSource(ctx context.Context, sourceID int64) error {
	ret := _m.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementForSource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVocabularyRepo_DecrementForSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementForSource'
type MockVocabularyRepo_DecrementForSource_Call struct {
	*mock.Call
}

// DecrementForSource is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID int64
func (_e *MockVocabularyRepo_Expecter) DecrementForSource(ctx interface{}, sourceID interface{}) *MockVocabularyRepo_DecrementForSource_Call {
	return &MockVocabularyRepo_DecrementForSource_Call{Call: _e.mock.On("DecrementForSource", ctx, sourceID)}
}

func (_c *MockVocabularyRepo_DecrementForSource_Call) Run(run func(ctx context.Context, sourceID int64)) *MockVocabularyRepo_DecrementForSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockVocabularyRepo_DecrementForSource_Call) Return(_a0 error) *MockVocabularyRepo_DecrementForSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVocabularyRepo_DecrementForSource_Call) RunAndReturn(run func(context.Context, int64) error) *MockVocabularyRepo_DecrementForSource_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementForSource provides a mock function with given fields: ctx, sourceID
func (_m *MockVocabularyRepo) IncrementForSource(ctx context.Context, sourceID int64) error {
	ret := _m.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementForSource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVocabularyRepo_IncrementForSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementForSource'
type MockVocabularyRepo_IncrementForSource_Call struct {
	*mock.Call
}

// IncrementForSource is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID int64
func (_e *MockVocabularyRepo_Expecter) IncrementForSource(ctx interface{}, sourceID interface{}) *MockVocabularyRepo_IncrementForSource_Call {
	return &MockVocabularyRepo_IncrementForSource_Call{Call: _e.mock.On("IncrementForSource", ctx, sourceID)}
}

func (_c *MockVocabularyRepo_IncrementForSource_Call) Run(run func(ctx context.Context, sourceID int64)) *MockVocabularyRepo_IncrementForSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockVocabularyRepo_IncrementForSource_Call) Return(_a0 error) *MockVocabularyRepo_IncrementForSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVocabularyRepo_IncrementForSource_Call) RunAndReturn(run func(context.Context, int64) error) *MockVocabularyRepo_IncrementForSource_Call {
	_c.Call.Return(run)
	return _c
}

// PruneZeros provides a mock function with given fields: ctx, sessionID
func (_m *MockVocabularyRepo) PruneZeros(ctx context.Context, sessionID int64) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for PruneZeros")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVocabularyRepo_PruneZeros_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneZeros'
type MockVocabularyRepo_PruneZeros_Call struct {
	*mock.Call
}

// PruneZeros is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
func (_e *MockVocabularyRepo_Expecter) PruneZeros(ctx interface{}, sessionID interface{}) *MockVocabularyRepo_PruneZeros_Call {
	return &MockVocabularyRepo_PruneZeros_Call{Call: _e.mock.On("PruneZeros", ctx, sessionID)}
}

func (_c *MockVocabularyRepo_PruneZeros_Call) Run(run func(ctx context.Context, sessionID int64)) *MockVocabularyRepo_PruneZeros_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockVocabularyRepo_PruneZeros_Call) Return(_a0 error) *MockVocabularyRepo_PruneZeros_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVocabularyRepo_PruneZeros_Call) RunAndReturn(run func(context.Context, int64) error) *MockVocabularyRepo_PruneZeros_Call {
	_c.Call.Return(run)
	return _c
}

// TopByIDF provides a mock function with given fields: ctx, sessionID, limit
func (_m *MockVocabularyRepo) TopByIDF(ctx context.Context, sessionID int64, limit int) ([]string, error) {
	ret := _m.Called(ctx, sessionID, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopByIDF")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]string, error)); ok {
		return rf(ctx, sessionID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []string); ok {
		r0 = rf(ctx, sessionID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, sessionID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVocabularyRepo_TopByIDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopByIDF'
type MockVocabularyRepo_TopByIDF_Call struct {
	*mock.Call
}

// TopByIDF is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
//   - limit int
func (_e *MockVocabularyRepo_Expecter) TopByIDF(ctx interface{}, sessionID interface{}, limit interface{}) *MockVocabularyRepo_TopByIDF_Call {
	return &MockVocabularyRepo_TopByIDF_Call{Call: _e.mock.On("TopByIDF", ctx, sessionID, limit)}
}

func (_c *MockVocabularyRepo_TopByIDF_Call) Run(run func(ctx context.Context, sessionID int64, limit int)) *MockVocabularyRepo_TopByIDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int))
	})
	return _c
}

func (_c *MockVocabularyRepo_TopByIDF_Call) Return(_a0 []string, _a1 error) *MockVocabularyRepo_TopByIDF_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVocabularyRepo_TopByIDF_Call) RunAndReturn(run func(context.Context, int64, int) ([]string, error)) *MockVocabularyRepo_TopByIDF_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVocabularyRepo creates a new instance of MockVocabularyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVocabularyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVocabularyRepo {
	mock := &MockVocabularyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
