//go:build mocks
// +build mocks

// Code generated by mockery. DO NOT EDIT.

package db

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionRepo is an autogenerated mock type for the SessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, filter
func (_m *MockSessionRepo) Count(ctx context.Context, filter ListSessionsFilter) (int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) (int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) int); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSessionRepo_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockSessionRepo_Expecter) Count(ctx interface{}, filter interface{}) *MockSessionRepo_Count_Call {
	return &MockSessionRepo_Count_Call{Call: _e.mock.On("Count", ctx, filter)}
}

func (_c *MockSessionRepo_Count_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockSessionRepo_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockSessionRepo_Count_Call) Return(_a0 int, _a1 error) *MockSessionRepo_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_Count_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) (int, error)) *MockSessionRepo_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, sess
func (_m *MockSessionRepo) Create(ctx context.Context, sess *Session) error {
	ret := _m.Called(ctx, sess)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *Session
func (_e *MockSessionRepo_Expecter) Create(ctx interface{}, sess interface{}) *MockSessionRepo_Create_Call {
	return &MockSessionRepo_Create_Call{Call: _e.mock.On("Create", ctx, sess)}
}

func (_c *MockSessionRepo_Create_Call) Run(run func(ctx context.Context, sess *Session)) *MockSessionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Session))
	})
	return _c
}

func (_c *MockSessionRepo_Create_Call) Return(_a0 error) *MockSessionRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepo_Create_Call) RunAndReturn(run func(context.Context, *Session) error) *MockSessionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, namespace, sessionTokenHash
func (_m *MockSessionRepo) Delete(ctx context.Context, namespace string, sessionTokenHash []byte) (DeleteSessionResult, error) {
	ret := _m.Called(ctx, namespace, sessionTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 DeleteSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (DeleteSessionResult, error)); ok {
		return rf(ctx, namespace, sessionTokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) DeleteSessionResult); ok {
		r0 = rf(ctx, namespace, sessionTokenHash)
	} else {
		r0 = ret.Get(0).(DeleteSessionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, namespace, sessionTokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionTokenHash []byte
func (_e *MockSessionRepo_Expecter) Delete(ctx interface{}, namespace interface{}, sessionTokenHash interface{}) *MockSessionRepo_Delete_Call {
	return &MockSessionRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, sessionTokenHash)}
}

func (_c *MockSessionRepo_Delete_Call) Run(run func(ctx context.Context, namespace string, sessionTokenHash []byte)) *MockSessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockSessionRepo_Delete_Call) Return(_a0 DeleteSessionResult, _a1 error) *MockSessionRepo_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_Delete_Call) RunAndReturn(run func(context.Context, string, []byte) (DeleteSessionResult, error)) *MockSessionRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with given fields: ctx, filter
func (_m *MockSessionRepo) DeleteAll(ctx context.Context, filter ListSessionsFilter) (DeleteSessionsResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 DeleteSessionsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) (DeleteSessionsResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) DeleteSessionsResult); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(DeleteSessionsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockSessionRepo_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockSessionRepo_Expecter) DeleteAll(ctx interface{}, filter interface{}) *MockSessionRepo_DeleteAll_Call {
	return &MockSessionRepo_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, filter)}
}

func (_c *MockSessionRepo_DeleteAll_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockSessionRepo_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockSessionRepo_DeleteAll_Call) Return(_a0 DeleteSessionsResult, _a1 error) *MockSessionRepo_DeleteAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_DeleteAll_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) (DeleteSessionsResult, error)) *MockSessionRepo_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, namespace, sessionID
func (_m *MockSessionRepo) DeleteByID(ctx context.Context, namespace string, sessionID int64) (DeleteSessionResult, error) {
	ret := _m.Called(ctx, namespace, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 DeleteSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (DeleteSessionResult, error)); ok {
		return rf(ctx, namespace, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) DeleteSessionResult); ok {
		r0 = rf(ctx, namespace, sessionID)
	} else {
		r0 = ret.Get(0).(DeleteSessionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, namespace, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockSessionRepo_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionID int64
func (_e *MockSessionRepo_Expecter) DeleteByID(ctx interface{}, namespace interface{}, sessionID interface{}) *MockSessionRepo_DeleteByID_Call {
	return &MockSessionRepo_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, namespace, sessionID)}
}

func (_c *MockSessionRepo_DeleteByID_Call) Run(run func(ctx context.Context, namespace string, sessionID int64)) *MockSessionRepo_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockSessionRepo_DeleteByID_Call) Return(_a0 DeleteSessionResult, _a1 error) *MockSessionRepo_DeleteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_DeleteByID_Call) RunAndReturn(run func(context.Context, string, int64) (DeleteSessionResult, error)) *MockSessionRepo_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, namespace, sessionTokenHash
func (_m *MockSessionRepo) Get(ctx context.Context, namespace string, sessionTokenHash []byte) (Session, error) {
	ret := _m.Called(ctx, namespace, sessionTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (Session, error)); ok {
		return rf(ctx, namespace, sessionTokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) Session); ok {
		r0 = rf(ctx, namespace, sessionTokenHash)
	} else {
		r0 = ret.Get(0).(Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, namespace, sessionTokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionTokenHash []byte
func (_e *MockSessionRepo_Expecter) Get(ctx interface{}, namespace interface{}, sessionTokenHash interface{}) *MockSessionRepo_Get_Call {
	return &MockSessionRepo_Get_Call{Call: _e.mock.On("Get", ctx, namespace, sessionTokenHash)}
}

func (_c *MockSessionRepo_Get_Call) Run(run func(ctx context.Context, namespace string, sessionTokenHash []byte)) *MockSessionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockSessionRepo_Get_Call) Return(_a0 Session, _a1 error) *MockSessionRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_Get_Call) RunAndReturn(run func(context.Context, string, []byte) (Session, error)) *MockSessionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockSessionRepo) List(ctx context.Context, filter ListSessionsFilter) ([]ManagedSession, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ManagedSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) ([]ManagedSession, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListSessionsFilter) []ManagedSession); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ManagedSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListSessionsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSessionRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ListSessionsFilter
func (_e *MockSessionRepo_Expecter) List(ctx interface{}, filter interface{}) *MockSessionRepo_List_Call {
	return &MockSessionRepo_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSessionRepo_List_Call) Run(run func(ctx context.Context, filter ListSessionsFilter)) *MockSessionRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ListSessionsFilter))
	})
	return _c
}

func (_c *MockSessionRepo_List_Call) Return(_a0 []ManagedSession, _a1 error) *MockSessionRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_List_Call) RunAndReturn(run func(context.Context, ListSessionsFilter) ([]ManagedSession, error)) *MockSessionRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ScanExpired provides a mock function with given fields: ctx, now
func (_m *MockSessionRepo) ScanExpired(ctx context.Context, now time.Time) ([]SessionRef, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ScanExpired")
	}

	var r0 []SessionRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]SessionRef, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []SessionRef); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SessionRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_ScanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanExpired'
type MockSessionRepo_ScanExpired_Call struct {
	*mock.Call
}

// ScanExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockSessionRepo_Expecter) ScanExpired(ctx interface{}, now interface{}) *MockSessionRepo_ScanExpired_Call {
	return &MockSessionRepo_ScanExpired_Call{Call: _e.mock.On("ScanExpired", ctx, now)}
}

func (_c *MockSessionRepo_ScanExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockSessionRepo_ScanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepo_ScanExpired_Call) Return(_a0 []SessionRef, _a1 error) *MockSessionRepo_ScanExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_ScanExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]SessionRef, error)) *MockSessionRepo_ScanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, namespace, sessionTokenHash, lastActivity
func (_m *MockSessionRepo) Touch(ctx context.Context, namespace string, sessionTokenHash []byte, lastActivity time.Time) error {
	ret := _m.Called(ctx, namespace, sessionTokenHash, lastActivity)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, time.Time) error); ok {
		r0 = rf(ctx, namespace, sessionTokenHash, lastActivity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepo_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockSessionRepo_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sessionTokenHash []byte
//   - lastActivity time.Time
func (_e *MockSessionRepo_Expecter) Touch(ctx interface{}, namespace interface{}, sessionTokenHash interface{}, lastActivity interface{}) *MockSessionRepo_Touch_Call {
	return &MockSessionRepo_Touch_Call{Call: _e.mock.On("Touch", ctx, namespace, sessionTokenHash, lastActivity)}
}

func (_c *MockSessionRepo_Touch_Call) Run(run func(ctx context.Context, namespace string, sessionTokenHash []byte, lastActivity time.Time)) *MockSessionRepo_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepo_Touch_Call) Return(_a0 error) *MockSessionRepo_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepo_Touch_Call) RunAndReturn(run func(context.Context, string, []byte, time.Time) error) *MockSessionRepo_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
